language: go

go:
  - "1.11.x"
  - "tip"

go_import_path: github.com/aws/aws-xray-daemon

services:
  - docker

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - make test

matrix:
  allow_failures:
    - go: tip
